<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\NobaRental.Backend.Data\NobaRental.Backend.Data.csproj" />
    <ProjectReference Include="..\NobaRental.Backend.Domain\NobaRental.Backend.Domain.csproj" />
  </ItemGroup>

</Project>
