// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NobaRental.Backend.Data;

#nullable disable

namespace NobaRental.Backend.Data.Migrations;

[DbContext(typeof(NobaRentalDbContext))]
partial class NobaRentalDbContextModelSnapshot : ModelSnapshot
{
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NobaRental.Backend.Data.Entities.CarEntity", b =>
                {
                    b.Property<string>("RegistrationNumber")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("CurrentMeterReadingKm")
                        .HasColumnType("bigint");

                    b.Property<string>("CurrentStationCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("RegistrationNumber");

                    b.HasIndex("CurrentStationCode");

                    b.ToTable("Car", (string)null);

                    b.HasData(
                        new
                        {
                            RegistrationNumber = "EV12345",
                            Category = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CurrentMeterReadingKm = 1000L,
                            CurrentStationCode = "OSL",
                            IsDeleted = false,
                            RowVersion = new byte[0],
                            Status = 1
                        },
                        new
                        {
                            RegistrationNumber = "BT20001",
                            Category = 2,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CurrentMeterReadingKm = 5000L,
                            CurrentStationCode = "OSL",
                            IsDeleted = false,
                            RowVersion = new byte[0],
                            Status = 1
                        },
                        new
                        {
                            RegistrationNumber = "TR99001",
                            Category = 3,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CurrentMeterReadingKm = 15000L,
                            CurrentStationCode = "BGO",
                            IsDeleted = false,
                            RowVersion = new byte[0],
                            Status = 1
                        });
                });

            modelBuilder.Entity("NobaRental.Backend.Data.Entities.RentalBookingEntity", b =>
                {
                    b.Property<long>("BookingNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("BookingNumber"));

                    b.Property<decimal>("BaseDayRental")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BaseKmPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)");

                    b.Property<string>("CustomerSsn")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("PickupDateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("PickupMeterReadingKm")
                        .HasColumnType("bigint");

                    b.Property<string>("PickupStationCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTimeOffset?>("ReturnDateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("ReturnMeterReadingKm")
                        .HasColumnType("bigint");

                    b.Property<string>("ReturnStationCode")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal?>("TotalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("BookingNumber");

                    b.HasIndex("PickupStationCode");

                    b.HasIndex("RegistrationNumber");

                    b.HasIndex("ReturnStationCode");

                    b.ToTable("RentalBooking", (string)null);
                });

            modelBuilder.Entity("NobaRental.Backend.Data.Entities.StationEntity", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Code");

                    b.ToTable("Station", (string)null);

                    b.HasData(
                        new
                        {
                            Code = "OSL",
                            City = "Oslo",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Oslo Airport Gardermoen",
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            Code = "BGO",
                            City = "Bergen",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Bergen Airport Flesland",
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            Code = "TRD",
                            City = "Trondheim",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Trondheim Airport Værnes",
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            Code = "SVG",
                            City = "Stavanger",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Stavanger Airport Sola",
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            Code = "OSLO-C",
                            City = "Oslo",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Oslo Central Station",
                            RowVersion = new byte[0]
                        });
                });

            modelBuilder.Entity("NobaRental.Backend.Data.Entities.CarEntity", b =>
                {
                    b.HasOne("NobaRental.Backend.Data.Entities.StationEntity", "CurrentStation")
                        .WithMany("Cars")
                        .HasForeignKey("CurrentStationCode")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CurrentStation");
                });

            modelBuilder.Entity("NobaRental.Backend.Data.Entities.RentalBookingEntity", b =>
                {
                    b.HasOne("NobaRental.Backend.Data.Entities.StationEntity", "PickupStation")
                        .WithMany("PickupBookings")
                        .HasForeignKey("PickupStationCode")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NobaRental.Backend.Data.Entities.CarEntity", "Car")
                        .WithMany("Bookings")
                        .HasForeignKey("RegistrationNumber")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NobaRental.Backend.Data.Entities.StationEntity", "ReturnStation")
                        .WithMany("ReturnBookings")
                        .HasForeignKey("ReturnStationCode")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Car");

                    b.Navigation("PickupStation");

                    b.Navigation("ReturnStation");
                });

            modelBuilder.Entity("NobaRental.Backend.Data.Entities.CarEntity", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("NobaRental.Backend.Data.Entities.StationEntity", b =>
                {
                    b.Navigation("Cars");

                    b.Navigation("PickupBookings");

                    b.Navigation("ReturnBookings");
                });
#pragma warning restore 612, 618
        }
    }
